"use strict";
var Dice = require('./Dice');
console.log("FROM test01.ts via the 'Dice' module");
var dice = new Dice();
var xx = dice.roll(1);
var yy = dice.roll(5);
var zz = dice.roll(3);
console.log(xx);
console.log(yy);
console.log(zz);
